version: '3.7'
services:
  work_history:
    build: .
    tty: true
    stdin_open: true
    ports:
    - 8083:8003
    volumes:
      - type: bind
        source: .
        target: /home
      - type: volume
        source: node_modules
        target: /home/node_modules

volumes:
  node_modules: